extends: "next/core-web-vitals"
env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  'prettier/prettier': warn
  '@next/next/no-img-element': off
